apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base


configMapGenerator:
- envs:
  - env/env.properties
  name: hyperexecute-env-vars

replacements:
- path: replacements/ingress.yml
#  - path: replacements/vault-name.yml
#  - path: replacements/tenantId.yml
#  - path: replacements/projectid.yml


patches:
- path: serviceaccount/sa-dispatcher.yml
  target:
    kind: ServiceAccount

