apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: job-artefacts-secret-provider-class
  labels:
    type: "microservice-secret"
spec:
  provider: gcp
  secretObjects:
    - secretName: job-artefacts-secrets
      type: Opaque
      data:
        - objectName: job-artefacts
          key: job-artefacts
  parameters:
    secrets: |
      - resourceName: "projects/712105902807/job-artefacts/versions/latest"
        fileName: "job-artefacts"
