apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: reception-secret-provider-class
  labels:
    type: "microservice-secret"
spec:
  provider: gcp
  secretObjects:
    - secretName: reception-secrets
      type: Opaque
      data:
        - objectName: reception
          key: reception
  parameters:
    secrets: |
      - resourceName: "projects/1011757057153/reception/versions/latest"
        fileName: "reception"
