apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: steward-secret-provider-class
  labels:
    type: "microservice-secret"
spec:
  provider: gcp
  secretObjects:
    - secretName: steward-secrets
      type: Opaque
      data:
        - objectName: steward
          key: steward
  parameters:
    secrets: |
      - resourceName: "projects/712105902807/steward/versions/latest"
        fileName: "steward"
