apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-secret-provider-class
  labels:
    type: "microservice-secret"
spec:
  provider: gcp
  secretObjects:
    - secretName: vault-secrets
      type: Opaque
      data:
        - objectName: vault
          key: vault
  parameters:
    secrets: |
      - resourceName: "projects/1011757057153/vault/versions/latest"
        fileName: "vault"
