apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: nevilm@lambdatest.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        azureDNS:
          subscriptionID: subscriptionID
          resourceGroupName: resourceGroupName
          hostedZoneName: hostedZoneName
          environment: AzurePublicCloud
          managedIdentity:
            clientID: clientID
