apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../production"

commonLabels:
  environment: prod

namespace: hyperexecute

patchesStrategicMerge:
  - "secret-providers/dispatcher.yml"
  - "secret-providers/lns.yml"
  - "secret-providers/logistics.yml"
  - "secret-providers/job-artefacts.yml"
  - "secret-providers/orchestrator.yml"
  - "secret-providers/reception.yml"
  - "secret-providers/steward.yml"
  - "secret-providers/vault.yml"