apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-secret-provider-class
  labels:
    type: "microservice-secret"
spec:
  provider: aws
  secretObjects:
    - secretName: vault-secrets
      type: Opaque
      data:
        - objectName: VAULT_DEPLOYMENT_ENV
          key: DEPLOYMENT_ENV
        - objectName: VAULT_LUMS_BASE_URL
          key: LUMS_BASE_URL
        - objectName: VAULT_MLD_ENV
          key: MLD_ENV
        - objectName: VAULT_Platform
          key: Platform
        - objectName: VAULT_REDIS_HOST
          key: REDIS_HOST
        - objectName: VAULT_REDIS_PORT
          key: REDIS_PORT
        - objectName: VAULT_SENTINEL_API_URL
          key: SENTINEL_API_URL
        - objectName: VAULT_AWS_REGION
          key: AWS_REGION

  parameters:
    objects:  |
      - objectName: template-sm-name
        objectType: "secretsmanager"
        jmesPath:
        - path: VAULT_DEPLOYMENT_ENV
          objectAlias: VAULT_DEPLOYMENT_ENV
        - path: VAULT_LUMS_BASE_URL
          objectAlias: VAULT_LUMS_BASE_URL
        - path: VAULT_MLD_ENV
          objectAlias: VAULT_MLD_ENV
        - path: VAULT_Platform
          objectAlias: VAULT_Platform
        - path: VAULT_REDIS_HOST
          objectAlias: VAULT_REDIS_HOST
        - path: VAULT_REDIS_PORT
          objectAlias: VAULT_REDIS_PORT
        - path: VAULT_SENTINEL_API_URL
          objectAlias: VAULT_SENTINEL_API_URL
        - path: VAULT_AWS_REGION
          objectAlias: VAULT_AWS_REGION
