apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  template:
    spec:
      containers:
        - name: vault
          volumeMounts:
            - name: vault-volumes
              mountPath: "/root/.env"
              subPath: ".env"
              readOnly: true
          envFrom:
            - secretRef:
                name: vault-secrets
      volumes:
        - name: vault-volumes
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "vault-secret-provider-class"
