apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: reception-secret-provider-class
  labels:
    type: "microservice-secret"
spec:
  provider: aws
  secretObjects:
    - secretName: reception-secrets
      type: Opaque
      data:
        - objectName: RECEPTION_BILLING_PLAN_LINK
          key: BILLING_PLAN_LINK
        - objectName: RECEPTION_DEPLOYMENT_ENV
          key: DEPLOYMENT_ENV
        - objectName: RECEPTION_LUMS_HOST
          key: LUMS_HOST
        - objectName: RECEPTION_REDIS_HOST
          key: REDIS_HOST
        - objectName: RECEPTION_SENTINEL_HOST
          key: SENTINEL_HOST
        - objectName: RECEPTION_AWS_ON_PREM_BUCKET
          key: AWS_ON_PREM_BUCKET
        - objectName: RECEPTION_IS_ONPREM_ENABLED
          key: IS_ONPREM_ENABLED
        - objectName: RECEPTION_AWS_ONPREM
          key: AWS_ONPREM
        - objectName: RECEPTION_AWS_DEFAULT_REGION
          key: AWS_DEFAULT_REGION
        - objectName: RECEPTION_CLOUD_PROVIDER
          key: CLOUD_PROVIDER
        - objectName: RECEPTION_REDIS_PORT
          key: REDIS_PORT
        - objectName: RECEPTION_DISPATCHER_HOST
          key: DISPATCHER_HOST
  parameters:
    objects:  |
      - objectName: template-sm-name
        objectType: "secretsmanager"
        jmesPath:
        - path: RECEPTION_BILLING_PLAN_LINK
          objectAlias: RECEPTION_BILLING_PLAN_LINK
        - path: RECEPTION_DEPLOYMENT_ENV
          objectAlias: RECEPTION_DEPLOYMENT_ENV
        - path: RECEPTION_LUMS_HOST
          objectAlias: RECEPTION_LUMS_HOST
        - path: RECEPTION_REDIS_HOST
          objectAlias: RECEPTION_REDIS_HOST
        - path: RECEPTION_SENTINEL_HOST
          objectAlias: RECEPTION_SENTINEL_HOST
        - path: RECEPTION_AWS_ON_PREM_BUCKET
          objectAlias: RECEPTION_AWS_ON_PREM_BUCKET
        - path: RECEPTION_IS_ONPREM_ENABLED
          objectAlias: RECEPTION_IS_ONPREM_ENABLED
        - path: RECEPTION_AWS_ONPREM
          objectAlias: RECEPTION_AWS_ONPREM
        - path: RECEPTION_AWS_DEFAULT_REGION
          objectAlias: RECEPTION_AWS_DEFAULT_REGION
        - path: RECEPTION_CLOUD_PROVIDER
          objectAlias: RECEPTION_CLOUD_PROVIDER
        - path: RECEPTION_REDIS_PORT
          objectAlias: RECEPTION_REDIS_PORT
        - path: RECEPTION_DISPATCHER_HOST
          objectAlias: RECEPTION_DISPATCHER_HOST

