apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperexecute-affinity
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hyenodepool
                operator: In
                values:
                - application
