apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hyperexecute
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:sujp21/test-repo-gcp-poc.git
    targetRevision: HEAD
    path: microservices/overlays/gcp/staging/
    plugin:
      # For either argocd-cm- or sidecar-installed CMPs, you can pass environment variables to the CMP.
      name: kustom-plugin
      env:
        - name: API_HOST_NAME
          value: apiHost
        - name: PROJECT_ID
          value: prj-prod-poc-hyperexecute-01
        - name: VAULT_NAME
          value: vault
        - name: GCP_REGION
          value: asia-south1
  destination: 
    server: https://kubernetes.default.svc
    namespace: hyperexecute

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      # selfHeal: true  # sync with remote repository
      prune: true # if delete yaml file on repo, then argocd will also delete it
