crds:
  install: true
  keep: false # this will remove all crds when helm is uninstalled

externalRedis:
  host: "argo-cd-redis-ha"

redis-ha:
  enabled: true
  exporter:
    enabled: false

  tolerations:
    - key: workload
      operator: Equal
      value: utility
      effect: NoSchedule
  affinity: |
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: workload
            operator: In
            values:
            - utility
  nodeSelector:
    workload: utility

  haproxy:
    enabled: false
    metrics:
      enabled: false

controller:
  replicas: 1

  tolerations:
    - key: workload
      operator: Equal
      value: utility
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: workload
            operator: In
            values:
            - utility
  nodeSelector:
    workload: utility

  resources:
    limits:
      cpu: '2'
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 1Gi

  serviceAccount:
    create: true
    automountServiceAccountToken: true

  metrics:
    enabled: false

server:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70

    behavior: {}
      # scaleDown:
      # stabilizationWindowSeconds: 300
      # policies:
      #   - type: Pods
      #     value: 1
      #     periodSeconds: 180
      # scaleUp:
      #   stabilizationWindowSeconds: 300
      #   policies:
      #   - type: Pods
      #     value: 2
      #     periodSeconds: 60

  tolerations:
    - key: workload
      operator: Equal
      value: utility
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: workload
            operator: In
            values:
            - utility
  nodeSelector:
    workload: utility

  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 125m
      memory: 128Mi

  metrics:
    enabled: false

  ingress:
    enabled: true
    annotations:
#      cert-manager.io/cluster-issuer: letsencrypt-prod
      ingress.kubernetes.io/ssl-redirect: "false"
      ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/tls-acme: "true"
    ingressClassName: "nginx"
    hosts:
      - argocd.test-hyperexecute.lambdatestinternal.com
    tls:
      - secretName: argocd-tls-certificate
        hosts:
          - argocd.test-hyperexecute.lambdatestinternal.com
    https: true
    ## to add grpc you have to add a new ingress


repoServer:
  extraArgs:
    - --repo-cache-expiration
    - 1m
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70
  resources:
    limits:
      cpu: '1'
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  tolerations:
    - key: workload
      operator: Equal
      value: utility
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: workload
            operator: In
            values:
            - utility
  nodeSelector:
    workload: utility
  clusterAdminAccess:
    enabled: true

applicationSet:
  replicas: 1
  resources:
    limits:
      cpu: '2'
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  tolerations:
    - key: workload
      operator: Equal
      value: utility
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: workload
            operator: In
            values:
            - utility
  nodeSelector:
    workload: utility

dex:
  enabled: true
  metrics:
    enabled: false
  serviceAccount:
    create: true

  tolerations:
    - key: workload
      operator: Equal
      value: utility
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: workload
            operator: In
            values:
            - utility
  nodeSelector:
    workload: utility

  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi
