apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: orchestrator-secret-provider-class
  labels:
    type: "microservice-secret"
spec:
  provider: gcp
  secretObjects:
    - secretName: orchestrator-secrets
      type: Opaque
      data:
        - objectName: .env
          key: orchestrator
  parameters:
    secrets: |
      - resourceName: "projects/1011757057153/secrets/orchestrator/versions/latest"
        fileName: ".env"
